In [2]:
import numpy as np
import pandas as pd

In [9]:
s = np.array([[1,2,3,4],[5,6,7,8]])
s

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
t = np.arange(24).reshape(6,4)
t

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
x = np.array([[0, 1, 2, 3],[4,5,6,7]])

# Square each value.
print(np.square(x))

# Square root of each value.
print(np.sqrt(x))

# Cosine of each value.
print(np.cos(x))


[[ 0  1  4  9]
 [16 25 36 49]]
[[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]]
[[ 1.          0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029  0.75390225]]


In [17]:
my_array = np.array([['Montgomery','Yellohammer state',52423],
                     ['Sacramento','Golden state',163707],
                     ['Oklahoma City','Sooner state',69960 ]])
df = pd.DataFrame(my_array)
df.columns = ['Capital', 'Nickname', 'Area']
df.index = ['Alabama', 'California', 'Oklahoma']
df

Capital           Nickname    Area
Alabama        Montgomery  Yellohammer state   52423
California     Sacramento       Golden state  163707
Oklahoma    Oklahoma City       Sooner state   69960

In [20]:
my_array = np.array([['Montgomery','Yellohammer state',52423],
                     ['Sacramento','Golden state',163707],
                     ['Oklahoma City','Sooner state',69960 ]])
df = pd.DataFrame(
    my_array,
    columns=['Capital', 'Nickname', 'Area'],
    index=['Alabama', 'California', 'Oklahoma'])
df

Capital           Nickname    Area
Alabama        Montgomery  Yellohammer state   52423
California     Sacramento       Golden state  163707
Oklahoma    Oklahoma City       Sooner state   69960

In [3]:
df = pd.read_csv('purchases.csv')
print(df)

  Unnamed: 0 country  ad_views  items_purchased
0     George      US        16                2
1       John     CAN        42                1
2     Thomas     CAN        32                0
3      James      US        13                8
4     Andrew     CAN        63                0
5     Martin      US        19                5
6    William      US        65                7
7    Zachary      US        23                3
8    Millard     CAN        16                0
9   Franklin      US        77                5


In [4]:
df.to_csv('my_data.csv')

In [9]:
df.to_csv(path'my_data.csv').filepath_or_buffer

AttributeError: 'NoneType' object has no attribute 'filepath_or_buffer'